/// Flutter icons AddLessCart
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AddLessCart
///      fonts:
///       - asset: fonts/AddLessCart.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AddLessCart {
  AddLessCart._();

  static const _kFontFam = 'AddLessCart';
  static const _kFontPkg = null;

  static  IconData minus = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static  IconData add = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
