/// Flutter icons BackButtonSVG
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BackButtonSVG
///      fonts:
///       - asset: fonts/BackButtonSVG.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BackButtonSVG {
  BackButtonSVG._();

  static const _kFontFam = 'BackButtonSVG';
  static const _kFontPkg = null;

  static IconData camera_back = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
