/// Flutter icons BarketRupee
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BarketRupee
///      fonts:
///       - asset: fonts/BarketRupee.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BarketRupee {
  BarketRupee._();

  static const _kFontFam = 'BarketRupee';
  static const _kFontPkg = null;

  static IconData basket = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static IconData rupee = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
