/// Flutter icons DashboardIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DashboardIcons
///      fonts:
///       - asset: fonts/DashboardIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DashboardIcons {
  DashboardIcons._();

  static const _kFontFam = 'DashboardIcons';
  static const _kFontPkg = null;

  static  IconData couch = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static  IconData furniture = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static  IconData bed = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static  IconData armchair = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
